---
- hosts: localhost
  become: yes
  remote_user: ec2-user
  tasks:
  - name: Adding lines into bashrc file
    lineinfile:
      path: ~/.bashrc
      line: 'NAME=wiprocluster.wipjenkins.uk'

  - name: Adding lines into bashrc file
    lineinfile:
      path: ~/.bashrc
      line: 'ZONES=us-west-2a,us-west-2b,us-west-2c'
      
  - name: Export commands
    shell: export ZONES=us-west-2a,us-west-2b,us-west-2c

  - name: Export commands
    shell: export NAME=wiprocluster.wipjenkins.uk
